---
title: "Monitoring Detail Fact Sheet"
output:
  html_document: default
  pdf_document: default
---

```{r, echo=FALSE}
data(salaries)
```

**Title**

```{r, echo=FALSE, comment=NA}
unique(index$project_title)
```

**Project ID**

```{r, echo=FALSE, comment=NA}
unique(index$project_id)
```

```{r, echo=FALSE, eval=FALSE, comment=NA}
unique(index$description)
```

```{r, echo=FALSE, eval=FALSE, comment=NA}
unique(index$deliverables)
```


```{r, echo=FALSE, eval=FALSE, comment=NA}
if (unique(index$objectives) == 0) {
  print("There are no identified objectives for this project")
} else 
unique(index$objectives)
```

```{r, echo=FALSE, eval=FALSE, comment=NA}
unique(index$status)
```

**Lead Contact**
```{r, echo=FALSE, comment=NA}
unique(index$lead_staff)
```


```{r, echo=FALSE, fig.caption="Figure 7: Line graph showing number of stations under different funding scenarios"}
plotSPA(om=om, salary=sal, which='predict', id=1093,funding= rep("NCP (A-base)",4),fundingChange=c(-25, -50, -75, -100))
```


```{r, echo=FALSE, fig.cap="Figure 2: Pie chart representing allocation of expenses for project over different years.", eval=FALSE}
plotSPA(index, id=id, which="omAllocationGeneral")
```







